# Generated by Django 3.0.7 on 2020-06-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_auto_20200625_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_title',
        ),
    ]
