# Generated by Django 3.0.7 on 2020-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
